// mockData.js
export const projects = [
  {
    id: 1,
    name: 'Project A',
    owner: 'John Doe',
    startDate: '01-09-2023',
    endDate: '01-12-2023',
  },
  {
    id: 2,
    name: 'Project B',
    owner: 'Jane Smith',
    startDate: '05-08-2023',
    endDate: '10-10-2023',
  },
];

export const issues = [
  {
    id: 1,
    title: 'Implement Authentication',
    description: 'Build the login system',
    assignee: 'Alice',
    priority: 'High',
    category: 'To-do',
    updatedAt: '2023-10-18',
  },
  {
    id: 2,
    title: 'Fix UI Bugs',
    description: 'Resolve padding and margin issues',
    assignee: 'Bob',
    priority: 'Medium',
    category: 'Development',
    updatedAt: '2023-10-16',
  },
  {
    id: 3,
    title: 'Write Unit Tests',
    description: 'Ensure code coverage for key modules',
    assignee: 'Charlie',
    priority: 'Low',
    category: 'Testing',
    updatedAt: '2023-10-15',
  },
  {
    id: 4,
    title: 'Deploy Application',
    description: 'Prepare deployment scripts for production',
    assignee: 'David',
    priority: 'High',
    category: 'Completed',
    updatedAt: '2023-10-10',
  },
  {
    id: 5,
    title: 'Refactor Codebase',
    description: 'Improve code readability and structure',
    assignee: 'Eve',
    priority: 'Medium',
    category: 'Development',
    updatedAt: '2023-10-14',
  },
  {
    id: 6,
    title: 'Optimize Database Queries',
    description: 'Speed up the query performance',
    assignee: 'Frank',
    priority: 'High',
    category: 'To-do',
    updatedAt: '2023-10-17',
  },
  {
    id: 7,
    title: 'Design New Dashboard UI',
    description: 'Create mockups for the new dashboard interface',
    assignee: 'Grace',
    priority: 'Medium',
    category: 'To-do',
    updatedAt: '2023-10-13',
  },
  {
    id: 8,
    title: 'Integrate Payment Gateway',
    description: 'Add support for multiple payment methods',
    assignee: 'Alice',
    priority: 'High',
    category: 'Development',
    updatedAt: '2023-10-12',
  },
  {
    id: 9,
    title: 'Conduct Security Audit',
    description: 'Review the application for security vulnerabilities',
    assignee: 'Bob',
    priority: 'Low',
    category: 'Testing',
    updatedAt: '2023-10-09',
  },
  {
    id: 10,
    title: 'Set Up CI/CD Pipeline',
    description: 'Automate build and deployment processes',
    assignee: 'David',
    priority: 'High',
    category: 'Completed',
    updatedAt: '2023-10-08',
  },
  {
    id: 11,
    title: 'Improve Accessibility',
    description: 'Enhance app accessibility for disabled users',
    assignee: 'Charlie',
    priority: 'Medium',
    category: 'To-do',
    updatedAt: '2023-10-14',
  },
  {
    id: 12,
    title: 'Update Documentation',
    description: 'Revise API and user guides',
    assignee: 'Eve',
    priority: 'Low',
    category: 'Completed',
    updatedAt: '2023-10-11',
  },
  {
    id: 13,
    title: 'Resolve Memory Leak',
    description: 'Identify and fix the memory issue in production',
    assignee: 'Frank',
    priority: 'High',
    category: 'To-do',
    updatedAt: '2023-10-19',
  },
  {
    id: 14,
    title: 'Upgrade Node.js Version',
    description: 'Migrate the project to the latest Node.js version',
    assignee: 'Grace',
    priority: 'Medium',
    category: 'Development',
    updatedAt: '2023-10-15',
  },
  {
    id: 15,
    title: 'Fix API Rate Limiting',
    description: 'Apply rate limits to the public API',
    assignee: 'Alice',
    priority: 'High',
    category: 'Development',
    updatedAt: '2023-10-18',
  },
];

